name: release

on:
  push:
    tags:
      - "v*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env:
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Set up Go 1.23
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.6
        id: go

      - name: Set Envs
        run: |
          echo GO_VERSION=$(go version | awk '{print $3;}') >> $GITHUB_ENV

      - name: Login to Snapcraft
        uses: samuelmeuli/action-snapcraft@v2

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          GO_VERSION: ${{ env.GITHUB_GO_VERSION }}
